version: "3.9"

services:
  api:
    build: .
    container_name: malware-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/sr

  db:
    image: postgres:16
    container_name: malware-db
    environment:
      POSTGRES_USER: malware
      POSTGRES_PASSWORD: malware
      POSTGRES_DB: malware
    #because is a supersmall project i will no follow the credential security rules

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
